RESULT = cipher_uncipher
SOURCES = uncipher.ml cipher.ml main.ml
OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)


# ocamlbuild -use-ocamlfind -pkg graphics ft_graphics.native
# ocambuild -clean