
RESULT = tictactoe
SOURCES = Board.mli Backend.mli UserInterface.mli Board.ml Backend.ml UserInterface.ml main.ml #unit_test_board.ml
OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)


# ocambuild -clean